### PR TITLE
Rebase from kubernetes/test-infra latest

### PR DESCRIPTION
**Pull request by wbrefvem**
@rawlingsj Not sure how we've been handling rebasing this, but it went through without any merge confilicts. I'm happy to do it as a regular chore if that makes sense.

### CODE REVIEW

**Comment by wbrefvem** [comment]
Okay, seems like our commits aren't in here for some reason. Hold until I can investigate.

**Comment by rawlingsj** [comment]
OK cool.  I tend to do a 
```
git remote add upstream git@github.com:kubernetes/test-infra.git
```
Then on the rebase I do a:
```
git fetch upstream
git rebase upstream/master
```
I wonder if we should avoid the regular rebasing until we have automated tests as it takes quite a lot to verify everything works without the automated tests?

**Comment by wbrefvem** [comment]
Okay yeah, that's how I did it.

That's a point well taken about automated testing, especially as our changes get more substantial. The thing I want to avoid is needing some upstream change and having to either cherry pick it from upstream or sift through a mountain of merge conflicts. Honestly there are few things I dread more! And yeah, manually testing everything every time we rebase is equally nightmarish.

**Pull request closed without merging**
